package.json, yarn.lock
closes #6 
removal of `babel-plugin-transform-runtime` still builds on node 4 via Circle on my fork and plugin works in example local test
added keywords to get us ready for upcoming Algolia powered [NPM search](https://github.com/algolia/npm-search)!
critically `gatsby-plugin`
See for example:
https://yarnpkg.com/en/packages?q=gatsby&p=1&keywords%5B0%5D=gatsby-plugin
=> remove babel-plugin-transform-runtime #6 add keywords for npm-search

package.json
Added a schedule to the renovate PRs for dev dependencies, and enabled automerging for everything but major version changes.
Is the schedule of once a month frequent enough, or should we merge more frequently?
=> [Chore] Reduce renovate noise

package.json
Reverts GraphCMS/gatsby-source-graphcms#39 in order to test the fix for `docker:disable`
=> Revert "chore(deps): pin docker digests"

src/__tests__/util.test.js, src/gatsby-node.js, src/util.js
This PR refactors how headers are created.
I found the existing method cause Authorization errors regardless if the dashboard URL was public, or was protected and a token was provided.
```
// This is the response from an 'open' URL
Error: Not Authorised!: {"response":{"errors":[{"message":"Not Authorised!","locations":[{"line":2,"column":11}],"path  ":["pages"]}],"data":null,"status":500},"request":{"query":"{\n          pages {\n            id\n            title\n            }\n        }"}}
```
``` 
// This is the response from a 'protected' URL with a token provided
TypeError: Cannot read property '1' of null 
```
This proposed change only includes headers keys if their values are provided.
=> Refactor creation of headers

demo/gatsby-config.js, demo/package.json, gatsby-source-graphcms/gatsby-node.js, gatsby-source-graphcms/package.json, yarn.lock
Use `gatsby-graphql-source-toolkit` to build Gatsby nodes for types from a remote GraphCMS project schema.
=> feat: Build Gatsby nodes

demo/gatsby-config.js, gatsby-source-graphcms/gatsby-node.js, gatsby-source-graphcms/package.json, yarn.lock
Uses `createRemoteFileNode` to build local file nodes for GraphCMS images.
Can be used with `gatsby-image` etc.
This features is opt in, must be enabled in `gatsby-config.js`:
```js
{
resolve: 'gatsby-source-graphcms',
options: {
downloadLocalImages: true
}
}
```
=> feat: Build files nodes for GraphCMS image assets

.github/workflows/release.yml, package.json
Use [`semantic-release`](https://github.com/semantic-release/semantic-release) to automate package versioning and publishing with GitHub Actions.
=> chore: Automate package publishing

gatsby-source-graphcms/gatsby-node.js, gatsby-source-graphcms/package.json, yarn.lock
When writing the GraphCMS queries to source data for nodes, use the root query fields from the GraphQL schema.
Previously these were compiled using the schema `type` names. However query fields can be specified by GraphCMS users during model creation so they may differ entirely from the model name/type.
=> fix: Use correct root query fields

gatsby-source-graphcms/gatsby-node.js, gatsby-source-graphcms/package.json, yarn.lock
HTML characters are escaped in JSON response for markdown fields, which prevents using components directly in CMS entries.
=> fix: Decode markdown field returned from GraphCMS

gatsby-source-graphcms/gatsby-node.js
There could be multiple RichText fields per type, so use the field key with `createNodeId()`.
Fixes #102.
=> fix: Ensure unique node ID is used when building MarkdownNodes

gatsby-source-graphcms/gatsby-node.js
Check if type has `locale` field as opposed to  checking for `locales` argument, which is now available on all types regardless of if localisation is present.
Fixes #123.
=> fix: Check if type has locale field

gatsby-source-graphcms/README.md, gatsby-source-graphcms/gatsby-node.js
* Adds `typePrefix` configuration value to be used during Gatsby node building to prevent any type conflicts. Defaults to `GraphCMS_`
* Add note to `README` to recommend using `fragmentsPath` when using multiple source plugin instances.
Using these 2 configuration values is **strongly** recommended if using multiple instances of the source plugin in a single Gatsby project.
=> feat: All configuration for multiple instances

demo/package.json, gatsby-source-graphcms/src/gatsby-node.js, yarn.lock
Use the new [`pluginOptionsSchema`](https://www.gatsbyjs.com/docs/configuring-usage-with-plugin-options#how-to-validate-plugin-options) API to validate provided plugin options. This is only available in `gatsby@2.25.0`, so we need to keep the previous safeguarding for older applications.
Fixes #144.
=> feat: Use pluginOptionsSchema

gatsby-source-graphcms/package.json, yarn.lock
Use `next` release tag. This should help when using `downloadLocalImages` option.
=> chore(deps): Bump gatsby-source-filesystem dependency

demo/graphcms-fragments/Category.graphql, demo/graphcms-fragments/Product.graphql, gatsby-source-graphcms/src/gatsby-node.js
Use `fileName` field on Asset type (if queried) to build local asset node.
The file name can't be determined from the CDN URL so this is required for more SEO compliant images.
=> feat: Use fileName field from Asset type when generating local file

gatsby-source-graphcms/src/gatsby-node.js
Update `pluginOptionsSchema` to ensure `locales` property has at least 1 item.
Also, removed some redundant configuration checking now we're using `pluginOptionsSchema`.
=> fix: Ensure `locale` option has items

.all-contributorsrc, gatsby-source-graphcms/README.md, package.json
This should satisfy the `@next` prerelease as mentioned here https://github.com/GraphCMS/gatsby-source-graphcms/pull/173#issuecomment-806779077
=> chore: update release branches

gatsby-source-graphcms/src/gatsby-node.js
Allow a null return value from the `gatsbyImageData` resolver, to support non-image asset nodes.
=> fix(gatsby-source-graphcms): Make `gatsbyImageData` nullable

gatsby-source-graphcms/src/gatsby-node.js
Revert a temp change to returning null until we have an improved gatsby image resolver.
=> fix: return null for non images

gatsby-source-graphcms/src/gatsby-node.js, gatsby-source-graphcms/src/util/reportPanic.js
**Changes proposed:**
After upgrading to Gatsby v3, the `reporter.panic` and `reporter.error` stopped working on the old-school way (passing the message and error as arguments to the function, as we've been doing). That's why it always displays a `[object Object] [object Object]` error message. After diving into this, I've found another way to use the reporter. 
In the screenshot below, there's the new error message (it can change depending on the problem):
**Additional context:**
Related to #187 
Ps: I'm also going to open an issue on the Gatsby repo to report this bug.
=> fix: error message not properly formatted
